# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_design/top_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_design || ORIG_REF_NAME==top_design} -quiet] -quiet

# IP: bd/top_design/ip/top_design_processing_system7_0_0/top_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_design_processing_system7_0_0 || ORIG_REF_NAME==top_design_processing_system7_0_0} -quiet] -quiet

# XDC: bd/top_design/ip/top_design_processing_system7_0_0/top_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_design_processing_system7_0_0 || ORIG_REF_NAME==top_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/top_design/top_design_ooc.xdc
